// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
    id, pipe_id, status_code, request_payload, transformed_payload
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateEventParams struct {
	ID                 uuid.UUID `json:"id"`
	PipeID             uuid.UUID `json:"pipe_id"`
	StatusCode         int32     `json:"status_code"`
	RequestPayload     []byte    `json:"request_payload"`
	TransformedPayload []byte    `json:"transformed_payload"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.PipeID,
		arg.StatusCode,
		arg.RequestPayload,
		arg.TransformedPayload,
	)
	return err
}

const createEventsBatch = `-- name: CreateEventsBatch :exec
INSERT INTO events (
    id,
    pipe_id,
    status_code,
    request_payload,
    transformed_payload
)
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::int[]),
    unnest($4::jsonb[]),
    unnest($5::jsonb[])
`

type CreateEventsBatchParams struct {
	Ids                 []uuid.UUID `json:"ids"`
	PipeIds             []uuid.UUID `json:"pipe_ids"`
	StatusCodes         []int32     `json:"status_codes"`
	RequestPayloads     [][]byte    `json:"request_payloads"`
	TransformedPayloads [][]byte    `json:"transformed_payloads"`
}

func (q *Queries) CreateEventsBatch(ctx context.Context, arg CreateEventsBatchParams) error {
	_, err := q.db.Exec(ctx, createEventsBatch,
		arg.Ids,
		arg.PipeIds,
		arg.StatusCodes,
		arg.RequestPayloads,
		arg.TransformedPayloads,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, pipe_id, status_code, request_payload, transformed_payload, created_at FROM events
WHERE pipe_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsParams struct {
	PipeID uuid.UUID `json:"pipe_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.PipeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.PipeID,
			&i.StatusCode,
			&i.RequestPayload,
			&i.TransformedPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
