// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID                 uuid.UUID `json:"id"`
	PipeID             uuid.UUID `json:"pipe_id"`
	StatusCode         int32     `json:"status_code"`
	RequestPayload     []byte    `json:"request_payload"`
	TransformedPayload []byte    `json:"transformed_payload"`
	CreatedAt          time.Time `json:"created_at"`
}

type Pipe struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	TargetUrl string     `json:"target_url"`
	JqFilter  string     `json:"jq_filter"`
	IsActive  bool       `json:"is_active"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt *time.Time `json:"created_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Username        string     `json:"username"`
	Email           string     `json:"email"`
	Password        *string    `json:"-"`
	OauthProvider   *string    `json:"oauth_provider"`
	OauthProviderID *string    `json:"oauth_provider_id"`
	AvatarUrl       *string    `json:"avatar_url"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at,omitempty"`
	TokenVersion    int32      `json:"token_version"`
}
