// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPipe = `-- name: CreatePipe :exec
INSERT INTO pipes (
   id, user_id, name, slug, target_url, jq_filter
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePipeParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	TargetUrl string    `json:"target_url"`
	JqFilter  string    `json:"jq_filter"`
}

func (q *Queries) CreatePipe(ctx context.Context, arg CreatePipeParams) error {
	_, err := q.db.Exec(ctx, createPipe,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.TargetUrl,
		arg.JqFilter,
	)
	return err
}

const deletePipe = `-- name: DeletePipe :execrows
UPDATE pipes
SET deleted_at = NOW(), is_active = false
WHERE id = $1 
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeletePipeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePipe(ctx context.Context, arg DeletePipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePipe, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPipeById = `-- name: GetPipeById :one
SELECT id, user_id, name, slug, target_url, jq_filter, is_active, created_at, updated_at, deleted_at FROM pipes
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetPipeByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPipeById(ctx context.Context, arg GetPipeByIdParams) (Pipe, error) {
	row := q.db.QueryRow(ctx, getPipeById, arg.ID, arg.UserID)
	var i Pipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.TargetUrl,
		&i.JqFilter,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPipeBySlug = `-- name: GetPipeBySlug :one
SELECT id, user_id, name, slug, target_url, jq_filter, is_active, created_at, updated_at, deleted_at FROM pipes
WHERE slug = $1
  AND is_active = true
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPipeBySlug(ctx context.Context, slug string) (Pipe, error) {
	row := q.db.QueryRow(ctx, getPipeBySlug, slug)
	var i Pipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.TargetUrl,
		&i.JqFilter,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPipes = `-- name: ListPipes :many
SELECT id, user_id, name, slug, target_url, jq_filter, is_active, created_at, updated_at, deleted_at FROM pipes
WHERE user_id = $1 AND deleted_at IS NULL
LIMIT $2 OFFSET $3
`

type ListPipesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPipes(ctx context.Context, arg ListPipesParams) ([]Pipe, error) {
	rows, err := q.db.Query(ctx, listPipes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipe{}
	for rows.Next() {
		var i Pipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.TargetUrl,
			&i.JqFilter,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipe = `-- name: UpdatePipe :one
UPDATE pipes
SET target_url = $3,
    jq_filter = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, slug, target_url, jq_filter, is_active, created_at, updated_at, deleted_at
`

type UpdatePipeParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TargetUrl string    `json:"target_url"`
	JqFilter  string    `json:"jq_filter"`
	IsActive  bool      `json:"is_active"`
}

func (q *Queries) UpdatePipe(ctx context.Context, arg UpdatePipeParams) (Pipe, error) {
	row := q.db.QueryRow(ctx, updatePipe,
		arg.ID,
		arg.UserID,
		arg.TargetUrl,
		arg.JqFilter,
		arg.IsActive,
	)
	var i Pipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.TargetUrl,
		&i.JqFilter,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
