// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPipesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateEventsBatch(ctx context.Context, arg CreateEventsBatchParams) error
	CreatePipe(ctx context.Context, arg CreatePipeParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserReturning(ctx context.Context, arg CreateUserReturningParams) (User, error)
	DeletePipe(ctx context.Context, arg DeletePipeParams) (int64, error)
	GetPipeById(ctx context.Context, arg GetPipeByIdParams) (Pipe, error)
	GetPipeBySlug(ctx context.Context, slug string) (Pipe, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error)
	IncrementUserTokenVersion(ctx context.Context, id uuid.UUID) error
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListPipes(ctx context.Context, arg ListPipesParams) ([]Pipe, error)
	LoginOAuthUser(ctx context.Context, arg LoginOAuthUserParams) (User, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdatePipe(ctx context.Context, arg UpdatePipeParams) (Pipe, error)
	VerifyPipeOwnership(ctx context.Context, arg VerifyPipeOwnershipParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
