// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username, password, email, avatar_url
) VALUES (
    $1, $2, $3, $4
)
`

type CreateUserParams struct {
	Username  string  `json:"username"`
	Password  *string `json:"-"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const createUserReturning = `-- name: CreateUserReturning :one
INSERT INTO users (
    username, password, email, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, email, password, oauth_provider, oauth_provider_id, avatar_url, created_at, updated_at, deleted_at, token_version
`

type CreateUserReturningParams struct {
	Username  string  `json:"username"`
	Password  *string `json:"-"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUserReturning(ctx context.Context, arg CreateUserReturningParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserReturning,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, oauth_provider, oauth_provider_id, avatar_url, created_at, updated_at, deleted_at, token_version FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, oauth_provider, oauth_provider_id, avatar_url, created_at, updated_at, deleted_at, token_version FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT id, username, email, password, oauth_provider, oauth_provider_id, avatar_url, created_at, updated_at, deleted_at, token_version FROM users
WHERE oauth_provider = $1 AND oauth_provider_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetUserByOAuthParams struct {
	OauthProvider   *string `json:"oauth_provider"`
	OauthProviderID *string `json:"oauth_provider_id"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.OauthProvider, arg.OauthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TokenVersion,
	)
	return i, err
}

const incrementUserTokenVersion = `-- name: IncrementUserTokenVersion :exec
UPDATE users
SET token_version = token_version + 1
WHERE id = $1
`

func (q *Queries) IncrementUserTokenVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserTokenVersion, id)
	return err
}

const loginOAuthUser = `-- name: LoginOAuthUser :one
INSERT INTO users (
    id,
    email,
    username,
    oauth_provider,
    oauth_provider_id,
    avatar_url
) VALUES (
    gen_random_uuid(),
    $1, $2, $3, $4, $5
)
ON CONFLICT (email)
DO UPDATE SET
    oauth_provider = COALESCE(users.oauth_provider, EXCLUDED.oauth_provider),
    oauth_provider_id = COALESCE(users.oauth_provider_id, EXCLUDED.oauth_provider_id),
    avatar_url = COALESCE(EXCLUDED.avatar_url, users.avatar_url),
    updated_at = NOW()
WHERE users.deleted_at IS NULL
RETURNING id, username, email, password, oauth_provider, oauth_provider_id, avatar_url, created_at, updated_at, deleted_at, token_version
`

type LoginOAuthUserParams struct {
	Email           string  `json:"email"`
	Username        string  `json:"username"`
	OauthProvider   *string `json:"oauth_provider"`
	OauthProviderID *string `json:"oauth_provider_id"`
	AvatarUrl       *string `json:"avatar_url"`
}

func (q *Queries) LoginOAuthUser(ctx context.Context, arg LoginOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, loginOAuthUser,
		arg.Email,
		arg.Username,
		arg.OauthProvider,
		arg.OauthProviderID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TokenVersion,
	)
	return i, err
}
